# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ActivityIndicatingNavigationItemExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActivityIndicatingNavigationItemExample
    pod 'ActivityIndicatingNavigationItem', :path => '../'

  target 'ActivityIndicatingNavigationItemExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
